name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build and Deploy App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        app_location: "web" # Diretório do frontend
        api_location: "server" # Diretório do backend Flask
        output_location: "" # Deixe vazio se não houver artefatos de saída